// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "DogsAID",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "DogsAID",
            targets: ["AppModule"],
            bundleIdentifier: "com.harshwardhan.DogsAID",
            teamIdentifier: "YD8V4N5AAK",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "Sources/AppModule",
            resources: [
                .copy("Resources/Assets.xcassets")
            ]
        )
    ],
    swiftLanguageModes: [.version("6")]
)
